name: Spirits of the Forest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.97343
title: Spirits of the Forest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#201513'
    - '#5c5040'
    - '#cf6109'
    - '#597d8f'
    - '#c6bd49'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
